
setwd("/Users/Charizard/Google Drive/Data Science/data/UCI HAR Dataset/")
activity <- read.table("activity_labels.txt")
colnames(activity) <- c("y","activity_name")
features <- read.table("features.txt")
features$V2 <- sub("\\(","",features$V2)
features$V2 <- sub("\\)","",features$V2)
trimmedfeatures <- features[-c(317:344,396:423,475:502),]
setwd("test")
subjecttest <- read.table("subject_test.txt")
colnames(subjecttest) <- c("subject")
Xtest <- read.table("X_test.txt")
Xtest <- select(Xtest, -(317:344))
Xtest <- select(Xtest, -(396:423))
Xtest <- select(Xtest, -(475:502))
colnames(Xtest) <- trimmedfeatures$V2
Ytest <- read.table("y_test.txt")
colnames(Ytest) <- "y"
setwd("../train")
subjecttrain <- read.table("subject_train.txt")
colnames(subjecttrain) <- c("subject")
Xtrain <- read.table("X_train.txt")
Xtrain <- select(Xtrain, -(317:344))
Xtrain <- select(Xtrain, -(396:423))
Xtrain <- select(Xtrain, -(475:502))
colnames(Xtrain) <- trimmedfeatures$V2
Ytrain <- read.table("y_train.txt")
colnames(Ytrain) <- "y"
library(dplyr)
test <- cbind(Xtest, subjecttest, Ytest)
train <- cbind(Xtrain, subjecttrain, Ytrain)
dataset <- rbind(test, train)
indices <- c(grep("mean|std", trimmedfeatures$V2, value = FALSE))
trimmeddataset <- select(dataset, c(indices,478,479))
joineddataset <- merge(trimmeddataset, activity, by.x="y", by.y="y")
dataset2 <- with(joineddataset, aggregate(x=joineddataset[,2:80], by=list(subject,activity_name), FUN=mean))
colnames(dataset2) <- c("subject","activity_name", colnames(dataset2[,3:81]))
colnames(dataset2)
setwd("../submission")
write.table(dataset2, "tidydata.txt", row.names = FALSE)
colnames(dataset2[,1:2]) <- c("subject","activity_name")